### ISSUE TITLE
Set up React Native infrastructure

### ISSUE THREAD

**Issue by brandonschabell** [PantryChef/PantryChef#18]
I was speaking with Melinda yesterday and she suggested we take a look at React Native for our ui framework. After looking into it more, I think it would be a really great option. Not only does it give us the power of React (which is just inherently awesome), but it also comes packed with some really cool development features like "Hot Reloading" which lets you see your changes live as you code them (with other frameworks, you typically have to recompile your app, restart your emulator, and go to that page.) Do we have any hangups about going this route? @avaidyam @KJ-Caramel

**Comment by KJ-Caramel** [comment]
I'm not against it but I legit don't know React Native or React that well...for React i'm like halfway through team treehouse's React Basics course. Its just something that would be unmarked territory for me

**Comment by KJ-Caramel** [comment]
I'm kinda more shaky on it as I think about it more and more. React Native + JS seems like what most software goes for but I haven't necessary heard of React Native + base android. Maybe in the future we could utilize this but as of right now I think the complexity of the project will greatly increase from it.

**Comment by brandonschabell** [comment]
@KJ-Caramel React Native seems to very common for mobile development. I'm not sure what the alternative would be.

**Comment by brandonschabell** [comment]
And for what it's worth, it's new territory for me as well. We could consider it a learning experience! :)

**Comment by KJ-Caramel** [comment]
lol uhhhhhhhhh. I mean i'm okay with it i guess....javascript is a very funky language, all i can say LOL. 
so the stack would be

- HTML
- CSS
- Javascript
- React
- DB? (please dont be mongodb)

**Comment by KJ-Caramel** [comment]
so i'm currently in the process of creating a test app with React Native and there are so many dependencies smh

**Comment by brandonschabell** [comment]
Java of course. MongoDB is out, so no worries there. The DB is SQLite which is an RDBMS.

**Comment by avaidyam** [comment]
Personal two-cents: The 2nd project group I had in CS ( @brandonschabell was in my first group) decided to use React and Swift for the backend on our project. I also had a side project using React called boilerbooks. I absolutely detested every second of React - it's a cool idea at first but it really bogs you down compared to a standard MVC app design (i.e. what Android and iOS frameworks use out-of-box like Activity, View, etc and ViewControllers on iOS).

Also, yeah @brandonschabell will remember but Realm was terrible to work with. They've added a lot of the features we needed 2 years ago but it's still not worth it over normal SQL. I ended up just learning how to write really nice SQL statements instead of dealing with wrappers.

**Comment by avaidyam** [comment]
Also, users will appreciate an actually fully native app, and trust me, they can tell when it's not. 👎 React Native is close but no cigar. 

@brandonschabell Do you remember the wiki stuff we added to Health365? There's a list of frameworks and "how we did X and Y and Z" mini-guides in there still!

**Comment by brandonschabell** [comment]
@avaidyam 
CC: @KJ-Caramel 
Thanks for the warning lol. Well I guess we could just go with the out-of-the box options for now, and if there's something we need that isn't supported, we can investigate other options down the road. 

Recommend closing this issue as "won't do". Any objections?

**Comment by brandonschabell** [comment]
Closing. Will not do.
